Sr2
Fa2019-3460-635/net-flow-and-circ pull request #27
Opened 2019-09-11 21:21 UTC by Andrew-Locke-Robinson

This branch changes the graph class to a different underlying data structure, adds parsing to the graph class, and adds functional breadth first search.

This branch also adds functionality to main.cpp in order to test from the command line different graphs.

2019-09-11 21:22 UTC, Andrew-Locke-Robinson commented
Notably, this branch REMOVES test cases for the graph class. I am currently in the process of learning how to add test cases for the new graph class implementation as well as for the BFS.

2019-09-11 23:00 UTC, esarver requested changes
Good work on this. Please view all of my comments as suggestions. Everything looks good, most of the stuff is stylistic.

2019-09-11 23:00 UTC, esarver commented on src/graph/graph.hpp
> +      std::string input; // input will hold each line, one at a time
I am probably being *super* picky but maybe `input` should be renamed to `input_line` for clarity?

2019-09-11 23:00 UTC, esarver commented on src/graph/graph.hpp
> +            if ((input[i] == ' ') || (input[i] == '\0')) {
There is nothing wrong with doing it this way, but a potentially easier to read way may be to do:
```c++
//...
while (std::getline(input_data, input))
{
    std::vector<edge> node_edges;
    std::vector<int> int_list;

    if(input.length() != 0)
    {
        std::stringstream line_stream = std::stringstream(input);
        std::string token;
        while(std::getline(line_stream, token, ' ')) {
            int_list.push_back(atoi(token.c_str()));
        }
    }
    //...
}
```

I think that should accomplish the same task and mitigates the need for pointer math.

2019-09-11 23:00 UTC, esarver commented on src/graph/graph.hpp
> +      return 1;
This should be `return true` since this function returns a `bool`

2019-09-11 23:00 UTC, esarver commented on src/graph/graph.hpp
> +        std::cout << "Node " << x << " is connecte to nodes:\n";
`connecte` is missing a `d`.

2019-09-11 23:00 UTC, esarver commented on test/graph/graph_tests.hpp
> +#include "graph.hpp"
I know you have a comment about this, but we should really recreate the tests.

2019-09-11 23:00 UTC, esarver commented on src/graph/bfs.hpp
> +      void reset()
As I stated in one of my other comments, please move the definition to the source file.

2019-09-11 23:00 UTC, esarver commented on src/graph/bfs.hpp
> +    /*
JavaDoc comment styling. If you want, I can make it that style. It'll take me 5 minutes. :)

2019-09-11 23:00 UTC, esarver commented on src/graph/bfs.cpp
> +  std::vector<std::vector<graph::Graph::edge>> adjacency_list = G.get_adjacency_list();
Maybe consider changing `std::vector<std::vector<graph::Graph::edge>>` to `auto` since we know what an `get_adjacency_list()` gives us.

2019-09-11 23:00 UTC, esarver commented on src/graph/bfs.cpp
> +#include "bfs.hpp"
It would probably be good to create a bfs_test soon.

2019-09-11 23:00 UTC, esarver commented on src/main.cpp
>      }
Consider adding a `default` that just prints something like `Feature not implemented`.

2019-09-11 23:00 UTC, esarver commented on src/main.cpp
> +      std::ifstream in_file(ProgramOptions::graph_filepath());
This all looks good!

2019-09-11 23:00 UTC, esarver commented on src/graph/graph.hpp
> +    int get_number_of_nodes()
Unless the compiler tells you differently, I think this method should be `const` since it doesn't change anything, not that it should matter a whole lot.

2019-09-11 23:00 UTC, esarver commented on src/graph/bfs.hpp
> +      void reset()
I think you can do that in the source file with 
```c++
void graph::Bfs::bfs_node::reset() //...
```

2019-09-13 21:35 UTC, esarver approved these changes

2019-09-13 21:36 UTC, merged